// apps/test-react/src/app/app.tsx
import { Component } from 'react';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.scss';
import {DsButton, DsCard, DsInput, DsAccordion, DsTable} from '@stencil/react';
import { defineCustomElements } from '@wc/stencil/loader';
defineCustomElements(window);
export const headers=['header1', 'header2', 'header3']

 export default function App(){
    return(
      <>

          <DsButton type="primary" size="large" width="auto" label="Button" disabled={false}></DsButton>
          <DsButton type="secondary" size="large" width="auto" label="Button" disabled={false}></DsButton>
          <DsButton type="tertiary" size="large" width="auto" label="Button" disabled={false}></DsButton>
          <DsButton type="emphasized" size="large" width="auto" label="Button" disabled={false}></DsButton>

          <DsButton type="primary" size="large" width="auto" label="Button" disabled={true}></DsButton>


          <DsButton type="primary" size="small" width="auto" label="Button" disabled={false}></DsButton>
          <DsButton type="secondary" size="small" width="auto" label="Button" disabled={false}></DsButton>
          <DsButton type="tertiary" size="small" width="auto" label="Button" disabled={false}></DsButton>
          <DsButton type="emphasized" size="small" width="auto" label="Button" disabled={false}></DsButton>

          <DsButton type="primary" size="small" width="auto" label="Button" disabled={true}></DsButton>

          <DsButton type="primary" size="large" width="full" label="Button" disabled={false}></DsButton>
          <DsButton type="secondary" size="large" width="full" label="Button" disabled={false}></DsButton>
          <DsButton type="tertiary" size="large" width="full" label="Button" disabled={false}></DsButton>
          <DsButton type="emphasized" size="large" width="full" label="Button" disabled={false}></DsButton>

          <DsButton type="primary" size="large" width="full" label="Button" disabled={true}></DsButton>

          <DsButton type="primary" size="small" width="full" label="Button" disabled={false}></DsButton>
          <DsButton type="secondary" size="small" width="full" label="Button" disabled={false}></DsButton>
          <DsButton type="tertiary" size="small" width="full" label="Button" disabled={false}></DsButton>
          <DsButton type="emphasized" size="small" width="full" label="Button" disabled={false}></DsButton>

          <DsButton type="primary" size="small" width="full" disabled></DsButton>

      <DsInput></DsInput>
      <DsAccordion description="Content that goes in the Accordion"></DsAccordion>
      <DsTable headers={headers}><tr><td>hi</td><td>hi</td><td>hi</td></tr></DsTable>
      <DsCard subtitle="Card Subtitle" cardTitle="Card Title"></DsCard>
     </>
    );
   
}

// apps/test-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'test-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'test-angular';
  headers=['header1','header2','header3'];
}

<ds-button type="secondary" size="large" width="auto" [disabled]="false">I'm a Button</ds-button>
<ds-button type="primary" size="large" width="auto"  [disabled]="false">I'm a Button</ds-button>
  <text-input></text-input>
  <ds-accordion color="blue" description="Content that goes in the accordion" title="Select me"></ds-accordion>
  <ds-table [headers]="headers"><tr><td>hi</td><td>hi</td><td>hi</td></tr></ds-table>
<ds-card subtitle="Card Subtitle" cardTitle="Card Title"></ds-card>
